version: 0.2

phases:
  pre_build:
    commands:
      - echo "Getting AWS Account ID"
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - echo "Account ID: $AWS_ACCOUNT_ID"
      - echo "Logging in to ECR"
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
    commands:
      - echo Extracting branch name...
      - BRANCH_NAME=$(echo $CODEBUILD_WEBHOOK_HEAD_REF | sed 's/refs\/heads\///')  # Extracts name of branch
      - echo Building the Docker image for branch $BRANCH_NAME...
      - docker build -t frozen-webapp:latest .
      - echo Tagging the Docker image...
      - docker tag frozen-webapp:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$BRANCH_NAME

  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$BRANCH_NAME
      
      