version: 0.2

pre_build:
  commands:
    - echo Logging in to Amazon ECR...
    - |
      aws ecr get-login-password --region $AWS_DEFAULT_REGION | \
      docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
    - echo Login successful.

  build:
    commands:
      - echo "Extracting branch name..."
      - BRANCH_NAME=$(echo $CODEBUILD_WEBHOOK_HEAD_REF | sed 's/refs\/heads\///')
      - echo "Branch: $BRANCH_NAME"
      - echo "Building Docker image..."
      - docker build -t frozen-webapp:latest .
      - echo "Tagging Docker image..."
      - docker tag frozen-webapp:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$BRANCH_NAME

  post_build:
    commands:
      - echo "Pushing Docker image..."
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$BRANCH_NAME